
export default class Constants {

  static readonly INPUT_ACCOUNT_LENGTH: number = 11;
  static readonly INPUT_PASSWORD_LENGTH: number = 8;
  static readonly COMMON_SPACE: number = 12;
  static readonly LOGIN_WAIT_TIME: number = 2000;
  static readonly SUCCESS_PAGE_URL: string = 'pages/SuccessPage';
  static readonly HOME_PAGE_URL: string = 'pages/HomePage';
  static readonly LOGIN_PAGE_URL: string = 'pages/LoginPage';
  static readonly VERIFY_PAGE_URL: string = 'pages/VerificationWindowPage';
  static readonly HOME_PAGE_ACTION: string = 'startHomePage';
  static readonly SUB_WINDOW_NAME: string = 'subWindow';
  static readonly STATUS_BAR_COLOR: string = '#F1F3F5';
  static readonly STATUS_BAR_CONTENT_COLOR: string = '#000000';
  static readonly SUB_WINDOW_WIDTH_RATIO: number = 0.93;
  static readonly SUB_WINDOW_ASPECT_RATIO: number = 1.25;
  static readonly FULL_PARENT: string = '100%';
  static readonly BUTTON_WIDTH: string = '86.7%';
  static readonly GRID_FOUR_COLUMNS: string = '1fr 1fr 1fr 1fr';
  static readonly GRID_TWO_ROWS: string = '1fr 1fr';
  static readonly GRID_TWO_COLUMNS: string = '1fr 1fr';
  static readonly GRID_THREE_ROWS: string = '1fr 1fr 1fr';
}

